### ISSUE TITLE
[Question] Using my own model

### ISSUE THREAD

**Issue by Oberonskii** [QIN2DIM/hcaptcha-challenger#125]
I made my own model for motorbusses, but I am not able to implement it. How can I do this?
I tried putting it in the model folder, which doesn't help at all.
Thanks!

**Comment by QIN2DIM** [comment]
```yaml
# ./src/objects.yaml
label_alias:
  # ...
  motorbusses: # model_name
    en: ["motorbus"] # challenge label
```
